### ISSUE TITLE
Nokogiri を require したスクリプトを exe 化すると実行時エラーとなる

### ISSUE THREAD

**Issue by fronoske** [nodai2hITC/neri#9]
開発再開ありがとうございます。今やほぼメンテナンスされなくなったOCRAに代わるexe化ツールとして期待しています。

さて、表題の通り [Nokogiri](https://nokogiri.org/) を require したスクリプトを exe 化すると、実行時にエラーとなってしまいます。
おそらく何らかのオプション指定を行えば解決するのだろうと思うのですが、残念ながらうまくいっていないため、アドバイスをいただければ幸いです。

以下にサンプルと再現手順を記します。

#### 環境
- OS: Windows 10 x64 20H2
- Ruby Installer 2 With Devkit で Ruby 3.1.2 x64 をインストール
- `ridk enable` 済み

#### nokogiri-test.rb
```
require 'nokogiri'
require 'open-uri'

doc = Nokogiri::HTML URI.open("https://www.github.com/"){|f| f.read}
p doc.title
```
#### スクリプトとして実行した結果
```
C:\work\test> ruby nokogiri-test.rb
"GitHub: Where the world builds software · GitHub"
```

#### neriでexe化
```
C:\work\test> neri --dll x64-ucrt-ruby310.dll nokogiri-test.rb
=== Running script 'nokogiri-test.rb' to check dependencies.
"GitHub: Where the world builds software · GitHub"
=== Script 'nokogiri-test.rb' end.
=== 239 files, 13890451 bytes dependencies.
=== Copying dependencies.
=== Creating exe_file '.\nokogiri-test.exe'.
=== Neri Finished.
```

#### exeを実行した結果
```
C:\work\test> nokogiri-test.exe
C:/work/test/system/lib/ruby/vendor_ruby/3.1.0/nokogiri/version/info.rb:34:in `compiled_libxml_version': uninitialized constant Nokogiri::VersionInfo::Gem (NameError)
        from C:/work/test/system/lib/ruby/vendor_ruby/3.1.0/nokogiri/version/info.rb:76:in `warnings'
        from C:/work/test/system/lib/ruby/vendor_ruby/3.1.0/nokogiri/version/info.rb:185:in `<class:VersionInfo>'
        from C:/work/test/system/lib/ruby/vendor_ruby/3.1.0/nokogiri/version/info.rb:7:in `<module:Nokogiri>'
        from C:/work/test/system/lib/ruby/vendor_ruby/3.1.0/nokogiri/version/info.rb:6:in `<top (required)>'
        from C:/work/test/system/lib/ruby/vendor_ruby/3.1.0/nokogiri/version.rb:4:in `require_relative'
        from C:/work/test/system/lib/ruby/vendor_ruby/3.1.0/nokogiri/version.rb:4:in `<top (required)>'
        from C:/work/test/system/lib/ruby/vendor_ruby/3.1.0/nokogiri.rb:117:in `require_relative'
        from C:/work/test/system/lib/ruby/vendor_ruby/3.1.0/nokogiri.rb:117:in `<top (required)>'
        from C:/work/test/system/lib/ruby/vendor_ruby/3.1.0/neri/runtime.rb:68:in `require'
        from C:/work/test/system/lib/ruby/vendor_ruby/3.1.0/neri/runtime.rb:68:in `require'
        from C:/work/test/system/lib/ruby/vendor_ruby/3.1.0/neri/runtime.rb:16:in `require'
        from C:/work/test/system/nokogiri-test.rb:1:in `<top (required)>'
        from C:/work/test/system/lib/ruby/vendor_ruby/3.1.0/neri/runtime.rb:82:in `load'
        from C:/work/test/system/lib/ruby/vendor_ruby/3.1.0/neri/runtime.rb:82:in `load'
        from C:/work/test/system/lib/ruby/vendor_ruby/3.1.0/neri/runtime.rb:20:in `load'
        from -e:2:in `<main>'

続行するには何かキーを押してください . . .
```

**Comment by nodai2hITC** [comment]
まず、Nokogiri は Rubygems を使っていることを前提としたコードが含まれているようで、Neri で exe 化する際に `--enable-gems` オプションで Rubygems を有効にする必要があるようです。

```
neri --dll x64-ucrt-ruby310.dll --enable-gems nokogiri-test.rb 
```

ただ、そうすると今度は「証明書が無い」とエラーが発生してしまいます。とりあえず、Ruby のインストール先にある「ssl/cert.pem」を Neri が作成した system フォルダ内に「ssl」フォルダを作成し、そこに cert.pem をコピーすると動作しました。
（これは面倒なので、今後のバージョンで自動的にこのファイルをコピーするオプションを追加するか、あるいはその動作をデフォルトにしてしまおうかと思います。）

ご報告ありがとうございました。

**Comment by nodai2hITC** [comment]
ところで `--dll x64-ucrt-ruby310.dll ` を付けないと上手く動きませんか？（私の環境では付けなくても動いているのですが…）

**Comment by fronoske** [comment]
早速のご調査・ご回答ありがとうございます！
`--enable-gems` オプションを付与して exeを生成したところ、（「証明書がない」ではなく）別のエラーが発生してしまいました……。

```
C:\work\test> nokogiri-test.exe
Ignoring stringio-3.0.2 because its extensions are not built. Try: gem pristine stringio --version 3.0.2
Ignoring strscan-3.0.4 because its extensions are not built. Try: gem pristine strscan --version 3.0.4
Ignoring io-wait-0.2.3 because its extensions are not built. Try: gem pristine io-wait --version 0.2.3
<internal:C:/work/test/system/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': 126: 指定されたモジュールが見つかりません。   - C:/work/test/system/lib/ruby/3.1.0/x64-mingw-ucrt/openssl.so (LoadError)
        from <internal:C:/work/test/system/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/work/test/system/lib/ruby/vendor_ruby/3.1.0/neri/runtime.rb:60:in `require'
        from C:/work/test/system/lib/ruby/vendor_ruby/3.1.0/neri/runtime.rb:16:in `require'
        from C:/work/test/system/lib/ruby/3.1.0/openssl.rb:13:in `<top (required)>'
        from <internal:C:/work/test/system/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:C:/work/test/system/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/work/test/system/lib/ruby/vendor_ruby/3.1.0/neri/runtime.rb:68:in `require'
        from C:/work/test/system/lib/ruby/vendor_ruby/3.1.0/neri/runtime.rb:16:in `require'
        from C:/work/test/system/lib/ruby/gems/3.1.0/gems/net-http-0.2.2/lib/net/https.rb:23:in `<top (required)>'
        from <internal:C:/work/test/system/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:C:/work/test/system/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/work/test/system/lib/ruby/vendor_ruby/3.1.0/neri/runtime.rb:68:in `require'
        from C:/work/test/system/lib/ruby/vendor_ruby/3.1.0/neri/runtime.rb:16:in `require'
        from C:/work/test/system/lib/ruby/3.1.0/open-uri.rb:298:in `open_http'
        from C:/work/test/system/lib/ruby/3.1.0/open-uri.rb:741:in `buffer_open'
        from C:/work/test/system/lib/ruby/3.1.0/open-uri.rb:212:in `block in open_loop'
        from C:/work/test/system/lib/ruby/3.1.0/open-uri.rb:210:in `catch'
        from C:/work/test/system/lib/ruby/3.1.0/open-uri.rb:210:in `open_loop'
        from C:/work/test/system/lib/ruby/3.1.0/open-uri.rb:151:in `open_uri'
        from C:/work/test/system/lib/ruby/3.1.0/open-uri.rb:721:in `open'
        from C:/work/test/system/lib/ruby/3.1.0/open-uri.rb:29:in `open'
        from C:/work/test/system/nokogiri-test.rb:4:in `<top (required)>'
        from C:/work/test/system/lib/ruby/vendor_ruby/3.1.0/neri/runtime.rb:82:in `load'
        from C:/work/test/system/lib/ruby/vendor_ruby/3.1.0/neri/runtime.rb:82:in `load'
        from C:/work/test/system/lib/ruby/vendor_ruby/3.1.0/neri/runtime.rb:20:in `load'
        from -e:2:in `<main>'
```
奇妙なのは、「見つかりません」と言われているその C:/work/test/system/lib/ruby/3.1.0/x64-mingw-ucrt/openssl.so は確かに存在することです。（この openssl.so は Ruby の lib 以下にあるものと同じものであることも確認しました。）

なお  `--dll x64-ucrt-ruby310.dll` はやはり必要で、これがないと exe 実行時に以下のエラーダイアログが表示されます。
![image](https://user-images.githubusercontent.com/13856413/185356133-4cdf06d6-d988-47c4-9e92-533d12dbbdab.png)

どうも諸々 @nodai2hITC  さんの環境と挙動が違っているようで、もう一度 Ruby のインストールから試そうと思います。
もし「これを試してみてほしい」といったものがあればお知らせください。

**Comment by nodai2hITC** [comment]
素の PC に Ruby を入れるところからやってみた結果、以下の方法で動作させることができました。

1. `neri --dll x64-ucrt-ruby310.dll,libcrypto-1_1-x64.dll,libssl-1_1-x64.dll --enable-gems nokogiri-test.rb` と、`libcrypto-1_1-x64.dll` と `libssl-1_1-x64.dll` も dll に追加する。
2. 上で書いたように、`(Ruby のインストール先)/ssl/cert.pem` を system/ssl にコピーする。

そもそも何故 x64-ucrt-ruby310.dll（新しく入れた環境ではこちらも再現しました）や libcrypto-1_1-x64.dll,libssl-1_1-x64.dll が手動で指定しないと入らないのかが まだ分かりませんが…原因を究明して、新しいバージョンを出したいと思います。

**Comment by fronoske** [comment]
詳しい調査ありがとうございます！
```
neri --dll x64-ucrt-ruby310.dll,libcrypto-1_1-x64.dll,libssl-1_1-x64.dll --enable-gems nokogiri-test.rb
```
私の環境でも上記コマンド＋ pem のコピーで見事に動作しました。本当にありがとうございます。
本issueとしてはCloseしたいと思います。

native extension周りは難しいですね。。。原因究明できることを祈っております。
